name : Practice Application on GitHub Actions
on :
    push:
        branches:
            - main
jobs:
    building-job:
        runs-on: windows-latest
        steps:
            - name: Find and Install Respository
              uses: actions/checkout@v2
            - name: Setup Node js
              uses: actions/setup-node@v2
              with:
                node-version: '22.18.0'
            - name: Install frontend Dependencies
              working-directory: ./frontend
              run: npm install
            - name: Install backend Dependencies
              working-directory: ./backend
              run: npm install
            - name: Run Build Command
              working-directory: ./frontend
              run: npm run build